"use strict";
const express = require("express");
const router = express.Router();
const authController = require("../controllers/auth");
const authorization = require("../middlewares/authorization");
const { authorizeUser } = authorization;
const { signIn, handleRefreshToken, logOut } = authController;
router.post("/signin", signIn);
router.post("/refreshToken", handleRefreshToken);
router.get("/logOut", authorizeUser, logOut);
module.exports = router;
