"use strict";
const express = require("express");
const router = express.Router();
const cartController = require("../controllers/cart");
const authorization = require("../middlewares/authorization");
const { authorizeUser } = authorization;
const { addToCart, removeFromCart, getCartItems, updateCartItemCount, deleteCart, getCarts, } = cartController;
router.get("/getCartItems", authorizeUser, getCartItems);
router.get("/getCarts", authorizeUser, getCarts);
router.put("/addToCart", authorizeUser, addToCart);
router.put("/removeFromCart", authorizeUser, removeFromCart);
router.put("/updateCartItemCount", authorizeUser, updateCartItemCount);
router.delete("/deleteCart", authorizeUser, deleteCart);
module.exports = router;
