"use strict";
const express = require("express");
const router = express.Router();
const creativeController = require("../controllers/creative");
const authorization = require("../middlewares/authorization");
const imageOptimization = require("../middlewares/imageOptimization");
const { authorizeUser, isCreative, isProductOwner } = authorization;
const { resizePhoto, uploadPhoto } = imageOptimization;
const { updateYearsOfExperience, updateFunFacts, updateIsAvailable, updatePersonalDescription, getOrders, setBrandName, setBrandLogo, getCreativeById, setupAccount, accountSetupDone, } = creativeController;
router.get("/getCreativeById", getCreativeById);
router.get("/getOrders", authorizeUser, isCreative, getOrders);
router.patch("/setupAccount", authorizeUser, isCreative, uploadPhoto.array("logo", 1), resizePhoto, setupAccount);
router.patch("/accountSetupDone", authorizeUser, isCreative, accountSetupDone);
router.patch("/updateYearsOfExperience", authorizeUser, isCreative, updateYearsOfExperience);
router.patch("/updateFunFacts", authorizeUser, isCreative, updateFunFacts);
router.patch("/updateIsAvailable", authorizeUser, isCreative, updateIsAvailable);
router.patch("/updatePersonalDescription", authorizeUser, isCreative, updatePersonalDescription);
router.patch("/setBrandName", authorizeUser, isCreative, setBrandName);
router.patch("/setBrandLogo", authorizeUser, isCreative, uploadPhoto.array("logo", 1), resizePhoto, setBrandLogo);
module.exports = router;
