"use strict";
const express = require("express");
const router = express.Router();
const authorization = require("../middlewares/authorization");
const reviewController = require("../controllers/review");
const { authorizeUser } = authorization;
const { giveReview, getCreativeReviews, getCustomerPostedReviews } = reviewController;
router.post("/giveReview", authorizeUser, giveReview);
router.get("/getCreativeReviews", getCreativeReviews);
router.get("/getCustomerPostedReviews", authorizeUser, getCustomerPostedReviews);
module.exports = router;
